### ISSUE TITLE
after upgradeto Home Assistant 2023.4.1  error i.setconfig is not a function

### ISSUE THREAD

**Issue by alvinleegit** [AmoebeLabs/swiss-army-knife-card#178]
![Screenshot 2023-04-07 123143](https://user-images.githubusercontent.com/116364823/230593931-c7741ccd-dd10-4fe4-aa65-a661aac1bba2.jpg)

**Comment by jgatringer** [comment]
exact problem here. please help with a patch.

I made a very big solar-card with the live-state of my house and that card is very important for me. :-(
For the moment i did a downgrade of Homeassistant to 2023-03...

<img width="449" alt="Bildschirmfoto 2023-04-07 um 20 27 50" src="https://user-images.githubusercontent.com/14805417/230659287-cbcbf1dc-6f41-4499-b600-4e1f99c95c2c.png">

**Comment by jwaz73** [comment]
Same issue here post upgrade to 2023.4.1 (Upgraded from 2023.3.3, skipped 2023.4.0).

Also seeing the following error in the HA core logs:
```
Logger: frontend.js.latest.202304061
Source: components/system_log/__init__.py:257
First occurred: 22:45:40 (52 occurrences)
Last logged: 22:56:58

http://x.x.x.x:8123/hacsfiles/swiss-army-knife-card/swiss-army-knife-card.js:693:758 TypeError: SwissArmyKnifeCard.lovelace is null
:0:0 ResizeObserver loop completed with undelivered notifications.
```

**Comment by cerebrate** [comment]
This and #177 appear to be caused by a change in 2023.4.0 that makes _custom-card-tools_ (which _swiss-army-knife-card_ uses) break. I have a pull request in against _custom-card-tools_ to fix this here:

https://github.com/custom-cards/custom-card-helpers/pull/73

In the meantime, to get _swiss-army-knife-card_ working, you can grab the file from here:

https://raw.githubusercontent.com/cerebrate/custom-card-helpers/master/dist/index.m.js

place it in the `www/community/swiss-army-knife-card/` directory under your Home Assistant configuration directory under the name `custom-card-helpers.m.js`, and then _very carefully_ find the part at the top of `swiss-army-knife-card.js` in the same directory that reads

`import{fireEvent,stateIcon,getLovelace}from"https://unpkg.com/custom-card-helpers@1.8.0/dist/index.m.js?module";`

and change that and only that to

`import{fireEvent,stateIcon,getLovelace}from"/local/community/swiss-army-knife-card/custom-card-helpers.m.js?module";`

Clear caches, reload resources, refresh, etc., and otherwise do the needful to get your browser to notice the changes, and you should have a working _swiss-army-knife-card_ again.

**Comment by tardich** [comment]
Does not work for me...  :-(

**Comment by RHG2208** [comment]
I;m sorry to say that's not working for me either....

**Comment by gonczil** [comment]
Solved, 1000 thanks and gratitude!

**Comment by tardich** [comment]
Worked on my side as well!   Thanks a lot for clarifying !  :-)

**Comment by jgatringer** [comment]
Thanks a lot. Works for me too!

**Comment by joeyjojo747** [comment]
I applied the fix and its working, expect in the companion app in iOS.
Is there something that I need to do to get it to work in the companion app in iOS?

**Comment by cerebrate** [comment]
@joeyjojo747 

To clear cache in the iOS app the way that makes this fix work, you have to go to

Settings -> Companion App -> Debugging -> Reset frontend cache

If you haven't tried that already, try that, and then reload it. It should work then.

**Comment by joeyjojo747** [comment]
@cerebrate that worked.
Thank you!!

**Comment by amyvgordon** [comment]
@cerebrate - thanks so much for this! I've followed your instructions all the way through, but I'm coming unstuck at the final gzip step. Any pointers as to how I create the new compressed file?

**Comment by stinobook** [comment]
> @cerebrate - thanks so much for this! I've followed your instructions all the way through, but I'm coming unstuck at the final gzip step. Any pointers as to how I create the new compressed file?

depends on your HASS installation, but the easiest way is to go into a terminal either via SSH or on your HASS itself and then go to the correct folder.
once there remove the old compressed file and run the gzip -k command to create a new one.

**Comment by stgallazzi** [comment]
After update SAK to version v1.0.0-rc.4 the error "i.setconfig is not a function" came back, and the above procedure to solve the problem no longer works.

**Comment by stgallazzi** [comment]
Thanks for the reply, but I don't understand what dependency is missing. I use storage mode, and resources were added through U.I.. Before the update it worked perfectly.

**Comment by cerebrate** [comment]
I can't repro this, I'm afraid. I just updated to v1.0.0-rc.4 here and it's working fine without having to repeat the procedure.

**Comment by AmoebeLabs** [comment]
This commit: https://github.com/AmoebeLabs/swiss-army-knife-card/commit/22197063f84e836468e13051d68595d1fdfbaff4 should have fixed this problem and is part of release https://github.com/AmoebeLabs/swiss-army-knife-card/releases/tag/v1.0.0-rc.4

So, @cerebrate , Thanks for your efforts! I totally missed that change, as I had a fixed HA version (docker) running. So pulling new versions did not work and I didn't see my own cards failing... 

@stgallazzi , did you clear your browser cache? And you should clear the frontend cache in the companion app for this change to get noticed by the mobile app.
